networks:
  shopapp:

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: shop-app
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - shopapp
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: shop-app-db
    environment:
      - MSSQL_SA_PASSWORD=Rpassw!1
      - ACCEPT_EULA=Y
    volumes:
      - ./.containers/database/data:/var/opt/mssql/data
      - ./.containers/database/log:/var/opt/mssql/log
      - ./.containers/database/secrets:/var/opt/mssql/secrets
    ports:
      - 1433:1433
    depends_on:
      - api
    networks:
      - shopapp